### ISSUE TITLE
Zoom on ROI

### ISSUE THREAD

**Issue by moonayyur** [zakodium-oss/pixelium#108]

**Comment by lpatiny** [comment]
- One column should be added in the list of roi containing a 'zoom' icon
- When clicked the image should focus on this ROI and it should the ROI should take maximum one third of the width or height

**Comment by lpatiny** [comment]
@stropitek You wanted to provide an example on how to use react-roi ?

**Comment by stropitek** [comment]
> @stropitek You wanted to provide an example on how to use react-roi ?

It's ready, I implemented the feature in react-roi and updated react-roi in pixelium.
