### ISSUE TITLE
Roi table could be more compact

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/pixelium#113]
![image](https://github.com/zakodium-oss/pixelium/assets/1484241/b272bafc-82c9-4653-a410-eb57bcaff30b)

We could change the background with odd / even css in order to easily identify the lines but it should be more compact.

**Comment by stropitek** [comment]
The `compact` and `striped` props of the Table component allow to do just that

**Comment by moonayyur** [comment]
I think we should add a boolean prop for `Table` in react-science to make the table header sticky

**Comment by stropitek** [comment]
> I think we should add a boolean prop for `Table` in react-science to make the table header sticky

SGTM, you can create an issue in react-science
