### ISSUE TITLE
apply selected filter to main image and add it in the pipeline operations list

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/pixelium#25]

**Comment by Xstoudi** [comment]
Taking your advices, opinions, preferences about how to execute the image pipeline should be handled state-wise and on a practical standpoint.

Naive way is to make a `usePipeline(image: Image): Image` that run it on the given image, but it could be useful to integrate it to the state to store intermediate images, access operations results, etc.

Another consideration : should pipeline operations be applied to every opened image? If yes, what behavior do we want if one of the pipeline operation succeed on an image and fail on another? Example: grey filter succeed on RGB image but fail (because it doesn't make sense) on a GREY image that is also opened.

**Comment by lpatiny** [comment]
A filter should probably have:
- name
- isApplicable kind of parameter
- active (true / false)
- parameters

We could activate deactivate a filter, delete a filter and if a filter can not be applied we can just skip it (and indicate that it is being skipped).

![image](https://github.com/zakodium-oss/pixelium/assets/1484241/56e80a12-4d60-4e7f-bb68-7acb7b88ae9c)

If we click on a specific filter we will go back in time to this specific filter and we could possibly change a parameter of this filter and reapply the pipeline till the end.

We could keep the intermediate images or redo the full processing starting from the original image that should anyway be kept.

Pipeline could be part of the 'settings' (related to a workspace) and changing the workspace could change the pipeline.

Pipeline could be named and called back in one click. I don't think that should be applied by default to all the images and I can imagine a drop down menu that allows to select the pipeline I want to apply on the currently selected image.

Some filters will have as output some other information (the region of interests). Not sure what is the best way to deal with it. In fact calculate the ROIs will not give another image but only ROIs. This is not a filter but rather an 'action' ?

**Comment by Xstoudi** [comment]
> Some filters will have as output some other information (the region of interests). Not sure what is the best way to deal with it. In fact calculate the ROIs will not give another image but only ROIs. This is not a filter but rather an 'action' ?

The question is, do we want an other pipeline operation after extracting the ROIs? If no, this is an 'action'. If yes, I'll have to think more about this peculiar case.

**Comment by Xstoudi** [comment]
Fixed by 641e7d5
