### ISSUE TITLE
Main panel view and zoom / pan

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/pixelium#3]
```[tasklist]
### Main panel view
- [ ] #19 
- [ ] #20
```

**Comment by lpatiny** [comment]
Many existing components. Here is a link with 10 of them:
- https://morioh.com/p/bca9c144354c

Would be nice if it works also on touch devices but I guess all of them support this feature.

I would also like that click twice zoom out to fit the available place.
The initial state should also take the available place
And would be better if the library is maintained.

**Comment by Xstoudi** [comment]
https://github.com/prc5/react-zoom-pan-pinch looks to match what we want here. It's the most up to date lib, seems to work on touch.

**Comment by Xstoudi** [comment]
`react-zoom-pan-pinch` seems to have trouble with shadow DOM, issue already exists: https://github.com/prc5/react-zoom-pan-pinch/issues/371

I'm currently trying to figure out what would be the best option between trying to find a lib that implement the same thing and supporting shadow DOM VS implementing a Canvas component that can display an image and zoom/pan in it.
