### ISSUE TITLE
save functionality

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/pixelium#33]
Save dropdown.
Can use `filelist-utils` to load seamlessly from filesystem or websource.

Data can be saved to `.pixelium` file (either raw or sourced)
Preferences can be included to file or in local storage.
View can be included to file or dropped.

**Comment by lpatiny** [comment]
There is now a new project, [file-collection](https://github.com/cheminfo/file-collection), that can save the `source` (where are the images coming from + data if needed) and the `state` as a `ium` file (in fact a zip file).

I think it is important to separate the source from the state itself but the `state` could be saved in the `ium` file.

Some ideas are available [here](https://github.com/cheminfo/file-collection/tree/9e48da204e347324a7dfc6da9010a4a0e3869fc4#using-in-a-react-component).
