### ISSUE TITLE
Data for tests

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/pixelium#36]
Here are some images that we can use to test the functionalities. They could be available from the left demo site.

[Archive.zip](https://github.com/zakodium-oss/pixelium/files/11525032/Archive.zip)

**Comment by lpatiny** [comment]
@Xstoudi Could you try to add in the left menu:

![image](https://github.com/zakodium-oss/pixelium/assets/1484241/0b440765-3ab6-427b-afc0-cb68f5ac8ffc)

'Dataset example' that would load the source: https://image-js.github.io/image-dataset-demo/

I plan to add more examples in this repository soon.

**Comment by stropitek** [comment]
[standard.zip](https://github.com/zakodium-oss/pixelium/files/11785059/standard.zip)

Those are images typically used in scientific publications about image processing algorithms.

**Comment by Xstoudi** [comment]
As mentionned during past feedback sessions, I'd prefer to implement the export first.
When I have the export implemented, then I'll know how `.pixelium` files are structured and I'll be able to import it.

**Comment by Xstoudi** [comment]
Fixed by 5778629c51fa2baf3348f378b9159fcc835497e1

**Comment by Xstoudi** [comment]
- [ ]
