### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/pixelium#38]
It's not possible to zoom past a certain level. I think it should be possible to zoom up to 1 pixel taking up all the space.

Also when doing so, you must make sure that the pixels are shown individually by using the proper interpolation algorithm. This can be done with the `image-rendering` CSS attribute.

![CleanShot 2023-06-14 at 10 06 46](https://github.com/zakodium-oss/pixelium/assets/4118690/dcd2e121-18a2-44af-b6a2-15712dbf8086)

**Comment by targos** [comment]
Another strategy that we can use to differentiate pixels (especially when they have identical or similar color is to draw a grid that separates them (only from a certain zoom level).

Example in Photoshop:
![CleanShot 2023-06-14 at 10 52 42](https://github.com/zakodium-oss/pixelium/assets/2352663/51c83a2c-c59e-49c1-8eab-97626368bfcd)

**Comment by Xstoudi** [comment]
I added more scale capability and set the `imageRendering: 'pixelated'` to the rendering canvas.

Problems remains : the more we zoom, the slower it zooms.

I think we should at some point fork and rewrite the [`react-map-interaction`](https://github.com/strateos/react-map-interaction) lib to refresh it and extend its capabilities.
