### ISSUE TITLE
Provide correct names to historgram

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/pixelium#39]
image-js-typscript has the following constants that would allow to display the name of the channel

https://github.com/image-js/image-js-typescript/blob/d0e1936362efdc1a88c5212be4a1ed768363a879/src/utils/constants/channelLabels.ts#L3

![image](https://github.com/zakodium-oss/pixelium/assets/1484241/94c33cfd-930d-43be-96e6-1b7edf725500)

**Comment by Xstoudi** [comment]
Channel labels are currently not exported outside of the library, I fixed it.
Waiting on https://github.com/image-js/image-js-typescript/pull/360
