### ISSUE TITLE
Use InfoPanel

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/pixelium#55]
Now that we have the new component in react-science

https://github.com/zakodium-oss/react-science/issues/526

Please implement it in this project and replace:

![image](https://github.com/zakodium-oss/pixelium/assets/1484241/e718ecb8-840d-4454-a893-03c638d99d32)

We have only one image with metadata: spheres.tif

**Comment by wadjih-bencheikh18** [comment]
I think it will be better if we make one Panel titled Information and it will have two subs general information and metadatas
![image](https://github.com/zakodium-oss/pixelium/assets/56769876/dfb8ed6a-aada-426b-ac50-f43514f3b798)
it will be like nmrium
![image](https://github.com/zakodium-oss/pixelium/assets/56769876/adeb6058-6b1a-42e3-a3cc-5a8fc2efe6a9)

**Comment by lpatiny** [comment]
Yes you should proceed replacing the 2 panels with your new information panel.
