### ISSUE TITLE
Surface annotation

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/pixelium#60]
The current implementation is too slow and we should rather go in the direction on embedding images

https://stackoverflow.com/questions/6249664/does-svg-support-embedding-of-bitmap-images

@wadjih-bencheikh18 Could you try this approach by creating hundreds of little images that are rectangle and for which we set a color ?

We will check after how to add this image-js-typescript in order to get an image (and a png) from a ROI.

**Comment by wadjih-bencheikh18** [comment]
I could implement it using `<path/>`

```tsx
const svgPath = useMemo(() => {
    const pathCommands: string[] = [];
    const mask = roi.getMask();
    const width = mask.width;
    const height = mask.height;
    for (let column = 0; column < width; column++) {
      for (let row = 0; row < height; row++) {
        if (mask.getBit(column, row) === 1) {
          pathCommands.push(`M${column},${row}`);

          if (row + 1 < height) {
            pathCommands.push(`V${row + 1}`);
          }
          if (column + 1 < width) {
            pathCommands.push(`H${column + 1}`);
          }
          pathCommands.push(`V${row}`);
        }
      }
    }
    return pathCommands.join(' ');
  }, []);
```
