### ISSUE TITLE
preview don't work on 16bit images

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/pixelium#64]
I tough I fixed it and it seems I did for the main view, but it's still not working in some modals for some reason.

Reproduction : open `spheres.tif` and try to add thresolding using masks.

**Comment by lpatiny** [comment]
Modify image-js-typescript so that by default we calculate on 2**8 histogram slots (and then we need to recalculate the correct threshold, multiply by 256 if 16 bits ?).
