### ISSUE TITLE
Overview with kind of images

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/pixelium#96]
![image](https://github.com/zakodium-oss/pixelium/assets/1484241/b19e6f9d-b955-4399-9093-13a83b1ef56d)

- width
- height
- bitDepths
- channels

Small icon for RGB or RGBA or GREY  or GREY A

**Comment by moonayyur** [comment]
I'm trying to use the `Table` component of react-science but I can't pass any propriety to `Table.Row` besides `style` and `hasBorder`
I would need to use `onClick` to change the image displayed and probably `css` prop to handle the hover highlight

**Comment by stropitek** [comment]
`Table.Row` should extend the props available on `tr` and spread them into `<tr>`
